### ISSUE TITLE
Multisensor question

### ISSUE THREAD

**Issue by GSternik** [rozenrod/multi_sensor_v1#1]
Hi, have you multisensor boards for sale? That's great project for IOT devices for home. I am interested to buy 2 of this.

**Comment by rozenrod** [comment]
sorry but i don't sell these modules

**Comment by sharathbk1912** [comment]
question : do the firmware available have low power mode enabled in them ? meaning do they sleep when not transmitting ?

**Comment by rozenrod** [comment]
If you want to use the firmware for battery power, then you need to purchase a license for the [PTVO ](https://ptvo.info/zigbee-configurable-firmware-features/premium/)firmware configurator or use your own.

**Comment by SLKNSK** [comment]
Give a detailed description of the circuit. Purpose of connectors J1 - J5

**Comment by rozenrod** [comment]
There is a schematic in the project article (https://rozenrod.github.io/project/multi_sensor_v1/).  There is no special purpose for connectors J1-j5, they can be used as desired, for example, connect a bme280 sensor.  Thanks to their firmware, they can be programmed for themselves.

**Comment by SLKNSK** [comment]
> There is a schematic in the project article (https://rozenrod.github.io/project/multi_sensor_v1/).  There is no special purpose for connectors J1-j5, they can be used as desired, for example, connect a bme280 sensor.  Thanks to their firmware, they can be programmed for themselves.

I'll ask the question differently.  You have 4 ready-made firmware.  Specifically for each of them what should be the scheme?  What connector is used for what?

**Comment by rozenrod** [comment]
I no longer recommend using built-in firmware. It is better to construct your in the PTVO designer
