### ISSUE TITLE
query how is read sensor intended to work ?

### ISSUE THREAD

**Issue by sharathbk1912** [rozenrod/multi_sensor_v1#2]
![image](https://user-images.githubusercontent.com/79350776/118795538-4d947400-b8b8-11eb-8ead-074316e5b235.png)

Reed switch is also pulling low and there is also pull down resistor on the p0.3.

What change does the module capture here ?

Is the firmware configured for internal high pull up ?

**Comment by rozenrod** [comment]
This anti-bounce circuit does not work on battery power, I recommend connecting directly to p0.3
